If the String we're about to analyze for highlighting is greater than 100MB, we don't send it to ES, we instead analyze it ourselves -- assuming that unicode work segementation and lowercase is "good enough" for highlighting.
This is necessary as very large text values can cause ES' analysis to generate a buffer of the returned JSON that's larger than 2G, which isn't allowed.  As such, there's no way to get the analyzed tokens back from ES.

It helps to prevent this ES error:

ERROR:  failed to analyze text for highlighting: ElasticsearchError(Some(400), "{\n  \"error\": {\n    \"root_cause\": [\n      {\n        \"type\": \"illegal_argument_exception\",\n        \"reason\": \"ReleasableBytesStreamOutput cannot hold more than 2GB of data\"\n      }\n    ],\n    \"type\": \"illegal_argument_exception\",\n    \"reason\": \"ReleasableBytesStreamOutput cannot hold more than 2GB of data\",\n    \"suppressed\": [\n      {\n        \"type\": \"illegal_state_exception\",\n        \"reason\": \"Failed to close the XContentBuilder\",\n        \"caused_by\": {\n          \"type\": \"i_o_exception\",\n          \"reason\": \"Unclosed object or array found\"\n        }\n      }\n    ]\n  },\n  \"status\": 400\n}")